from __future__ import annotations


def html() -> str:
    return r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Analyze Capture · InnAware PMS Emulator</title>
<style>
:root{font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#17202a;background:#eef1f4;--navy:#172b4d;--line:#d9e0e6;--muted:#677482;--green:#166534;--amber:#92400e;--red:#991b1b;--blue:#1d4ed8}*{box-sizing:border-box}body{margin:0}.wrap{max-width:1200px;margin:auto;padding:20px}.top{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.top h1{margin:0;font-size:27px}.muted{color:var(--muted)}.card{background:#fff;border:1px solid var(--line);border-radius:12px;padding:15px;margin-top:14px;box-shadow:0 2px 7px #0000000b}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:end}.row label{display:flex;flex-direction:column;gap:4px;font-size:12px;color:#52606d;min-width:140px;flex:1}select,button{font:inherit;border:1px solid #bdc8d2;border-radius:7px;padding:8px;background:#fff}button{cursor:pointer;background:var(--navy);color:#fff;border-color:var(--navy)}a.button{display:inline-block;text-decoration:none;background:#fff;color:var(--navy);border:1px solid #bdc8d2;border-radius:7px;padding:8px 11px}.notice{padding:10px 12px;border-radius:8px;background:#eff6ff;color:#1e3a8a;margin-top:14px}.metrics{display:flex;gap:8px;flex-wrap:wrap}.metric{background:#f7f9fb;border:1px solid #e5e9ee;border-radius:9px;padding:8px 11px;min-width:120px}.metric b{display:block;font-size:17px}.finding{border:1px solid var(--line);border-radius:10px;padding:12px;margin-top:10px}.finding.error{border-left:5px solid var(--red)}.finding.warning,.finding.warn{border-left:5px solid var(--amber)}.finding.info{border-left:5px solid var(--blue)}.finding h4{margin:0 0 5px}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#e8edf3;font-size:12px;margin:2px}.pill.good{background:#dcfce7;color:var(--green)}.pill.warn{background:#fef3c7;color:var(--amber)}.pill.bad{background:#fee2e2;color:var(--red)}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;padding:7px;border-bottom:1px solid #edf0f2;vertical-align:top}th{color:#52606d;font-size:11px;text-transform:uppercase;letter-spacing:.04em}.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;white-space:pre-wrap;word-break:break-word}.small{font-size:12px}.errorbox{display:none;color:var(--red);background:#fef2f2;border-radius:8px;padding:10px;margin-top:10px}.empty{color:var(--muted);padding:12px 0}ul{margin:6px 0 0 20px;padding:0}@media(max-width:700px){.wrap{padding:12px}.row>*{width:100%}}
</style></head><body><div class="wrap">
<div class="top"><div><h1>Analyze Capture</h1><div class="muted">Read-only PBX↔PMS interoperability findings from the selected interface's bounded wire capture.</div></div><a class="button" href="/">Back to Operator Console</a></div>
<div class="notice"><b>Read-only analysis.</b> This view does not start or stop interfaces, change profiles, alter transport settings, send traffic, or write configuration. Capture analysis is separate from the live session-state diagnostics stream.</div>
<section class="card"><div class="row"><label>Interface<select id="interface"></select></label><label>Capture window<select id="limit"><option>50</option><option>100</option><option selected>200</option><option>500</option></select></label><button id="analyze">Analyze Capture</button></div><div id="error" class="errorbox"></div></section>
<section id="summary-card" class="card" style="display:none"><h3 style="margin-top:0">Selected endpoint</h3><div id="summary" class="metrics"></div></section>
<section id="observations-card" class="card" style="display:none"><h3 style="margin-top:0">Observed evidence</h3><div id="observations"></div></section>
<section id="findings-card" class="card" style="display:none"><h3 style="margin-top:0">Technician findings</h3><div id="findings"></div></section>
</div>
<script>
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path){let r=await fetch(path,{headers:{'Accept':'application/json'}});if(!r.ok){let t=await r.text();throw new Error(t||r.statusText)}return await r.json()}
function metric(label,value){let shown=value===null||value===undefined||value===''?'—':value;return `<div class="metric"><span class="small muted">${esc(label)}</span><b>${esc(shown)}</b></div>`}
function valueText(v){if(v===null||v===undefined)return '—';if(typeof v==='string')return v;try{return JSON.stringify(v)}catch(_){return String(v)}}
function renderObservations(items){let entries=Object.entries(items||{});if(!entries.length)return '<div class="empty">No bounded observations are available.</div>';return `<table><thead><tr><th>Observation</th><th>Value</th></tr></thead><tbody>${entries.map(([k,v])=>`<tr><td>${esc(k)}</td><td class="mono">${esc(valueText(v))}</td></tr>`).join('')}</tbody></table>`}
function renderList(items,empty){let values=Array.isArray(items)?items:[];return values.length?`<ul>${values.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<div class="small muted">${esc(empty)}</div>`}
function findingClass(severity){let s=String(severity||'info').toLowerCase();return s==='error'||s==='critical'?'error':s==='warning'||s==='warn'?'warning':'info'}
function renderFinding(f){let tags=Array.isArray(f.tags)?f.tags:[];return `<article class="finding ${findingClass(f.severity)}"><div><span class="pill ${findingClass(f.severity)==='error'?'bad':findingClass(f.severity)==='warning'?'warn':'good'}">${esc(f.severity||'info')}</span><span class="pill">confidence: ${esc(f.confidence||'unknown')}</span>${tags.map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div><h4>${esc(f.title||f.id||'Finding')}</h4><div>${esc(f.summary||'')}</div><div class="small"><b>Evidence</b>${renderList(f.evidence,'No evidence excerpt supplied.')}</div><div class="small"><b>Corrective action</b>${renderList(f.suggested_actions,'No corrective action supplied.')}</div><div class="small muted mono">${esc(f.id||'')}</div></article>`}
function renderReport(r){$('summary-card').style.display='block';$('observations-card').style.display='block';$('findings-card').style.display='block';$('summary').innerHTML=metric('Interface',r.interface_name)+metric('Protocol',r.protocol)+metric('Configured framing',r.configured_framing)+metric('Personality',r.personality_id)+metric('Emulation role',r.emulation_role)+metric('Findings',(r.findings||[]).length);$('observations').innerHTML=renderObservations(r.observations);$('findings').innerHTML=(r.findings||[]).map(renderFinding).join('')||'<div class="empty">No findings in this capture window. That does not prove protocol compatibility; it only means no configured diagnostic rule fired.</div>'}
async function loadInterfaces(){let d=await api('/api/v1/interfaces');let items=Array.isArray(d.interfaces)?d.interfaces:[];$('interface').innerHTML=items.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} · ${esc(x.protocol||'')} · ${esc(x.transport||'')}</option>`).join('');if(!items.length){$('interface').innerHTML='<option value="">No interfaces configured</option>';$('analyze').disabled=true}}
async function analyze(){let name=$('interface').value,limit=$('limit').value;if(!name)return;$('error').style.display='none';$('analyze').disabled=true;try{let r=await api(`/api/v1/interfaces/${encodeURIComponent(name)}/capture-diagnostics?limit=${encodeURIComponent(limit)}`);renderReport(r)}catch(e){$('error').textContent=e.message;$('error').style.display='block'}finally{$('analyze').disabled=false}}
$('analyze').onclick=analyze;loadInterfaces().catch(e=>{$('error').textContent=e.message;$('error').style.display='block'});
</script></body></html>'''
