from __future__ import annotations


def html() -> str:
    return r'''<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>InnAware PMS Emulator</title>
<style>
:root{font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#17202a;background:#eef1f4}
body{margin:0}.wrap{max-width:1320px;margin:auto;padding:22px}.top{display:flex;gap:12px;align-items:center;justify-content:space-between}
h1{margin:0}.muted{color:#677482}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:16px;margin-top:16px}
.card{background:white;border:1px solid #d9e0e6;border-radius:12px;padding:16px;box-shadow:0 2px 7px #0000000b}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:end}
label{display:flex;flex-direction:column;gap:4px;font-size:12px;color:#52606d;min-width:110px;flex:1}input,select,button,textarea{font:inherit;border:1px solid #bdc8d2;border-radius:7px;padding:8px;background:white}
button{cursor:pointer;background:#172b4d;color:white;border-color:#172b4d}button.secondary{background:white;color:#172b4d}button.danger{background:#9b1c1c;border-color:#9b1c1c}
.status{font-weight:700}.online{color:#15803d}.listening{color:#1d4ed8}.error{color:#b91c1c}.stopped{color:#6b7280}
table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;padding:7px;border-bottom:1px solid #edf0f2;vertical-align:top}pre{background:#111827;color:#d1fae5;padding:10px;border-radius:8px;max-height:300px;overflow:auto;white-space:pre-wrap}
.small{font-size:12px}.full{grid-column:1/-1}.pill{display:inline-block;padding:2px 7px;border-radius:999px;background:#e8edf3;font-size:12px}textarea{min-height:66px}
</style></head><body><div class="wrap">
<div class="top"><div><h1>InnAware PMS Emulator</h1><div class="muted">PMS, PBX and call-accounting integration test console</div></div><div id="health" class="pill">Loading...</div></div>
<div class="grid">
<section class="card full"><h3>Interfaces</h3><div id="interfaces"></div><hr><div class="row">
<label>Name<input id="if-name" value="fias-test"></label><label>Purpose<select id="if-purpose"><option value="pms">PMS</option><option value="call_accounting">Call Accounting</option></select></label>
<label>Protocol<select id="if-protocol"></select></label><label>Transport<select id="if-transport"><option value="tcp_server">TCP Server</option><option value="tcp_client">TCP Client</option><option value="serial">Serial</option></select></label>
<label>Host/Bind<input id="if-host" value="0.0.0.0"></label><label>Port<input id="if-port" type="number" value="5001"></label><label>Serial<input id="if-serial" placeholder="COM3 or /dev/ttyUSB0"></label>
<label>Framing<select id="if-framing"><option value="raw">Raw</option><option value="crlf" selected>CRLF</option><option value="stx_etx">STX/ETX</option><option value="stx_etx_bcc">STX/ETX+BCC</option></select></label>
<button onclick="createInterface()">Create</button></div><div id="if-error" class="error small"></div></section>
<section class="card"><h3>Guest Operations</h3><div class="row"><label>Interface<select id="guest-if"></select></label><label>Action<select id="guest-action"><option value="checkin">Check In</option><option value="checkout">Check Out</option><option value="move">Room Move</option><option value="wakeup_set">Set Wakeup</option><option value="wakeup_cancel">Cancel Wakeup</option></select></label></div>
<div class="row"><label>Room<input id="guest-room" value="101"></label><label>Last Name<input id="guest-last" value="Smith"></label><label>First Name<input id="guest-first" value="John"></label><label>New Room<input id="guest-new-room"></label></div>
<div class="row"><label>Wakeup HHMM<input id="guest-wakeup"></label><button onclick="sendGuest()">Send Guest Event</button></div><pre id="guest-result">Ready.</pre></section>
<section class="card"><h3>Call Generator</h3><div class="row"><label>Interface<select id="call-if"></select></label><label>Mode<select id="call-mode"><option value="raw">Immediate</option><option value="transaction">ENQ/ACK Transaction</option></select></label></div>
<div class="row"><label>Room<input id="call-room" value="101"></label><label>Number<input id="call-number" value="16155551212"></label><label>Duration sec<input id="call-duration" type="number" value="185"></label><label>Cost<input id="call-cost" type="number" step=".01" value="2.75"></label></div>
<button onclick="sendCall()">Send Call Record</button><pre id="call-result">Ready.</pre></section>
<section class="card full"><h3>Live Capture</h3><div class="row"><label>Interface<select id="capture-if" onchange="refreshCaptures()"></select></label><button class="secondary" onclick="refreshCaptures()">Refresh</button><label><span>Auto refresh</span><select id="auto"><option value="0">Off</option><option value="1" selected>On</option></select></label></div><div id="captures"></div></section>
</div></div>
<script>
let protocols=[]; async function api(path,opts={}){let r=await fetch(path,opts); if(!r.ok){let t=await r.text(); throw new Error(t||r.statusText)} if(r.status===204)return null; return await r.json()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function boot(){let h=await api('/api/v1/health');document.getElementById('health').textContent=`v${h.version} · ${h.interfaces} interface(s)`;let p=await api('/api/v1/protocols');protocols=p.protocols.filter(x=>x.implemented);renderProtocols();await refreshInterfaces();}
function renderProtocols(){let purpose=document.getElementById('if-purpose').value;document.getElementById('if-protocol').innerHTML=protocols.filter(x=>x.purpose===purpose).map(x=>`<option>${esc(x.id)}</option>`).join('')}
document.getElementById('if-purpose').onchange=renderProtocols;
async function refreshInterfaces(){let d=await api('/api/v1/interfaces');let rows=d.interfaces.map(x=>`<tr><td><b>${esc(x.name)}</b><br><span class="small muted">${esc(x.protocol)} · ${esc(x.transport)}</span></td><td><span class="status ${esc(x.state)}">${esc(x.state)}</span><br><span class="small">${esc(x.peer||'')}</span></td><td>${esc(x.connected_clients)}</td><td><button class="secondary" onclick="startIf('${esc(x.name)}')">Start</button> <button class="secondary" onclick="stopIf('${esc(x.name)}')">Stop</button> <button class="danger" onclick="deleteIf('${esc(x.name)}')">Delete</button></td></tr>`).join('');document.getElementById('interfaces').innerHTML=`<table><thead><tr><th>Interface</th><th>Status</th><th>Clients</th><th>Actions</th></tr></thead><tbody>${rows||'<tr><td colspan="4" class="muted">No interfaces configured.</td></tr>'}</tbody></table>`;let opts=d.interfaces.map(x=>`<option>${esc(x.name)}</option>`).join('');['guest-if','call-if','capture-if'].forEach(id=>{let e=document.getElementById(id),v=e.value;e.innerHTML=opts;if([...e.options].some(o=>o.value===v))e.value=v});refreshCaptures();}
async function createInterface(){let transport=document.getElementById('if-transport').value,host=document.getElementById('if-host').value;let body={name:document.getElementById('if-name').value,purpose:document.getElementById('if-purpose').value,protocol:document.getElementById('if-protocol').value,transport,enabled:true,bind_host:transport==='tcp_server'?host:'0.0.0.0',host:transport==='tcp_client'?host:null,port:Number(document.getElementById('if-port').value)||null,serial_device:transport==='serial'?document.getElementById('if-serial').value:null,options:{framing:document.getElementById('if-framing').value}};try{await api('/api/v1/interfaces',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});document.getElementById('if-error').textContent='';await refreshInterfaces()}catch(e){document.getElementById('if-error').textContent=e.message}}
async function startIf(n){await api(`/api/v1/interfaces/${encodeURIComponent(n)}/start`,{method:'POST'});refreshInterfaces()} async function stopIf(n){await api(`/api/v1/interfaces/${encodeURIComponent(n)}/stop`,{method:'POST'});refreshInterfaces()} async function deleteIf(n){if(confirm(`Delete ${n}?`)){await api(`/api/v1/interfaces/${encodeURIComponent(n)}`,{method:'DELETE'});refreshInterfaces()}}
async function sendGuest(){let n=document.getElementById('guest-if').value;if(!n)return;let b={action:document.getElementById('guest-action').value,room:document.getElementById('guest-room').value,last_name:document.getElementById('guest-last').value,first_name:document.getElementById('guest-first').value,new_room:document.getElementById('guest-new-room').value||null,wakeup_time:document.getElementById('guest-wakeup').value||null};try{let d=await api(`/api/v1/interfaces/${encodeURIComponent(n)}/send/guest-event`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});document.getElementById('guest-result').textContent=JSON.stringify(d,null,2)}catch(e){document.getElementById('guest-result').textContent=e.message}}
async function sendCall(){let n=document.getElementById('call-if').value;if(!n)return;let mode=document.getElementById('call-mode').value,b={room:document.getElementById('call-room').value,number:document.getElementById('call-number').value,duration_seconds:Number(document.getElementById('call-duration').value),cost:Number(document.getElementById('call-cost').value),call_type:'D'};let suffix=mode==='transaction'?'send/call-record-transaction':'send/call-record';try{let d=await api(`/api/v1/interfaces/${encodeURIComponent(n)}/${suffix}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});document.getElementById('call-result').textContent=JSON.stringify(d,null,2)}catch(e){document.getElementById('call-result').textContent=e.message}}
async function refreshCaptures(){let n=document.getElementById('capture-if').value;if(!n){document.getElementById('captures').innerHTML='';return}try{let d=await api(`/api/v1/interfaces/${encodeURIComponent(n)}/captures?limit=100`);let rows=d.captures.slice().reverse().map(x=>`<tr><td>${esc(x.timestamp)}</td><td><b>${esc(x.direction.toUpperCase())}</b></td><td>${esc(x.note||'')}</td><td><code>${esc(x.hex)}</code><br><span class="small">${esc(x.text)}</span></td></tr>`).join('');document.getElementById('captures').innerHTML=`<table><thead><tr><th>Time</th><th>Dir</th><th>Note</th><th>Payload</th></tr></thead><tbody>${rows}</tbody></table>`}catch(e){document.getElementById('captures').textContent=e.message}}
setInterval(()=>{if(document.getElementById('auto').value==='1'){refreshInterfaces()}},2000);boot().catch(e=>document.getElementById('health').textContent=e.message);
</script></body></html>'''
