from __future__ import annotations


def html() -> str:
    return r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>InnAware PMS Emulator</title>
<style>
:root{font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#17202a;background:#eef1f4;--navy:#172b4d;--line:#d9e0e6;--muted:#677482;--green:#15803d;--blue:#1d4ed8;--red:#b91c1c;--amber:#a16207}
*{box-sizing:border-box}body{margin:0}.wrap{max-width:1500px;margin:auto;padding:20px}.top{display:flex;gap:12px;align-items:center;justify-content:space-between;flex-wrap:wrap}.top h1{margin:0;font-size:27px}.muted{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:14px;margin-top:14px}.card{grid-column:span 6;background:white;border:1px solid var(--line);border-radius:12px;padding:15px;box-shadow:0 2px 7px #0000000b}.full{grid-column:1/-1}.third{grid-column:span 4}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:end;margin:7px 0}label{display:flex;flex-direction:column;gap:4px;font-size:12px;color:#52606d;min-width:105px;flex:1}input,select,button,textarea{font:inherit;border:1px solid #bdc8d2;border-radius:7px;padding:8px;background:white;min-width:0}button{cursor:pointer;background:var(--navy);color:white;border-color:var(--navy);white-space:nowrap}button.secondary{background:white;color:var(--navy)}button.danger{background:#9b1c1c;border-color:#9b1c1c}button.good{background:#166534;border-color:#166534}button:disabled{opacity:.55;cursor:not-allowed}.status{font-weight:750;text-transform:uppercase;font-size:12px}.online{color:var(--green)}.listening,.ready{color:var(--blue)}.error{color:var(--red)}.stopped{color:#6b7280}.connecting,.reconnecting,.starting{color:var(--amber)}
table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;padding:7px;border-bottom:1px solid #edf0f2;vertical-align:top}th{color:#52606d;font-size:11px;text-transform:uppercase;letter-spacing:.04em}pre{background:#111827;color:#d1fae5;padding:10px;border-radius:8px;max-height:300px;overflow:auto;white-space:pre-wrap;margin:8px 0}.small{font-size:12px}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#e8edf3;font-size:12px}.pill.good{background:#dcfce7;color:#166534}.pill.warn{background:#fef3c7;color:#92400e}.pill.bad{background:#fee2e2;color:#991b1b}.metrics{display:flex;gap:8px;flex-wrap:wrap;margin:8px 0}.metric{background:#f7f9fb;border:1px solid #e5e9ee;border-radius:9px;padding:8px 11px;min-width:105px}.metric b{display:block;font-size:18px}.room-board{display:grid;grid-template-columns:repeat(auto-fill,minmax(155px,1fr));gap:8px}.room{border:1px solid #dce3e8;border-radius:9px;padding:9px;background:#fafbfc;cursor:pointer}.room:hover{border-color:#8497aa}.room.occupied{background:#ecfdf5;border-color:#a7f3d0}.room.dirty{box-shadow:inset 4px 0 #d97706}.room.outoforder{background:#fef2f2;border-color:#fecaca}.room-num{font-weight:800;font-size:16px}.room-sub{font-size:11px;color:#5d6b78;margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.split{display:flex;justify-content:space-between;gap:8px}.notice{padding:8px 10px;border-radius:7px;background:#eff6ff;color:#1e3a8a;margin:7px 0}.errorbox{color:#991b1b;background:#fef2f2;border-radius:7px;padding:7px;display:none}.tabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.tabs button.active{background:var(--navy);color:white}.tabs button:not(.active){background:white;color:var(--navy)}.hide{display:none}.mono{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}.nowrap{white-space:nowrap}.scroll{overflow:auto}.selected-room{outline:2px solid var(--blue)}
@media(max-width:1000px){.card,.third{grid-column:1/-1}.wrap{padding:12px}}
</style></head><body><div class="wrap">
<div class="top"><div><h1>InnAware PMS Emulator</h1><div class="muted">Cross-platform hotel PMS, PBX and call-accounting integration laboratory</div></div><div><span id="health" class="pill">Loading...</span> <span id="save-state" class="pill good">Persistent state</span></div></div>
<div class="grid">
<section class="card full"><div class="split"><div><h3 style="margin-top:0">Property Laboratory</h3><div class="muted small">The property database is the emulator source of truth. Wire transmission is optional and does not own hotel state.</div></div><button id="seed-demo" class="secondary">Seed Demo Hotel</button></div>
<div class="row"><label>Property<select id="property-select"></select></label><button id="refresh-property" class="secondary">Refresh</button><label>New ID<input id="property-id" value="test-hotel"></label><label>New Name<input id="property-name" value="Test Hotel"></label><label>Timezone<input id="property-tz" value="America/Chicago"></label><button id="create-property">Create Property</button></div><div id="property-error" class="errorbox"></div><div id="property-metrics" class="metrics"></div></section>

<section class="card full"><div class="split"><h3 style="margin:0">Room Board</h3><div class="row" style="margin:0"><label style="max-width:90px">Start<input id="bulk-start" type="number" value="101"></label><label style="max-width:80px">Count<input id="bulk-count" type="number" value="20"></label><button id="bulk-rooms" class="secondary">Add Rooms</button></div></div><div id="room-board" class="room-board" style="margin-top:10px"></div></section>

<section class="card"><h3>Front Desk / Guest Operations</h3><div class="notice small">Property mode is optional. Select no property to send direct protocol-debug events through the chosen PMS interface without creating rooms or guests.</div><div class="row"><label>PMS interface (required for direct debug)<select id="guest-if"></select></label><label>Room<input id="guest-room" value="101"></label><label>New Room<input id="guest-new-room" value="102"></label></div><div class="row"><label>Last Name<input id="guest-last" value="Smith"></label><label>First Name<input id="guest-first" value="John"></label><label>Language<input id="guest-language" placeholder="EN"></label></div><div class="row"><button data-hotel-op="checkin" class="good">Check In</button><button data-hotel-op="checkout" class="secondary">Check Out</button><button data-hotel-op="move" class="secondary">Move Room</button></div>
<hr><div class="row"><label>Wakeup HHMM<input id="wakeup-time" value="0630"></label><label>Date YYMMDD<input id="wakeup-date" placeholder="optional"></label><button data-hotel-op="wakeup" class="secondary">Set Wakeup</button><button data-hotel-op="cancel-wakeup" class="secondary">Cancel Wakeup</button></div><pre id="guest-result">Select a property for stateful testing, or choose a PMS interface and leave Property unselected for direct debug.</pre></section>

<section class="card"><h3>Room Operations</h3><div class="row"><label>Room<input id="room-op-room" value="101"></label><label>Housekeeping<select id="room-hk"><option>clean</option><option>dirty</option><option>inspected</option><option>pickup</option><option>out_of_order</option><option>unknown</option></select></label><button id="set-room-status" class="secondary">Update Status</button></div><div class="row"><label>Restriction<input id="room-restriction" placeholder="guest / local / none"></label><label>DND<select id="room-dnd"><option value="">No change</option><option value="true">On</option><option value="false">Off</option></select></label><label>MWI count<input id="room-mwi" type="number" min="0" placeholder="no change"></label></div><div class="row"><label>Language<input id="room-language" placeholder="no change"></label><label>Voicemail<select id="room-vm"><option value="">No change</option><option>active</option><option>clear</option><option>disabled</option></select></label><button id="set-room-controls" class="secondary">Update Controls</button></div><pre id="room-result">Ready.</pre></section>

<section class="card full"><h3>Interfaces</h3><div id="interfaces" class="scroll"></div><hr><div class="row"><label>Name<input id="if-name" value="fias-test"></label><label>Purpose<select id="if-purpose"><option value="pms">PMS</option><option value="call_accounting">Call Accounting</option></select></label><label>Protocol<select id="if-protocol"></select></label><label>Property<select id="if-property"></select></label></div><div class="row"><label>Transport<select id="if-transport"><option value="tcp_server">TCP Server</option><option value="tcp_client">TCP Client</option><option value="serial">Serial</option></select></label><label>Host / Bind<input id="if-host" value="0.0.0.0"></label><label>Port<input id="if-port" type="number" value="5001"></label><label>Serial<select id="if-serial"><option value="">Select port</option></select></label></div><div class="row"><label>Baud<input id="if-baud" type="number" value="9600"></label><label>Data bits<select id="if-data"><option>8</option><option>7</option><option>6</option><option>5</option></select></label><label>Parity<select id="if-parity"><option>N</option><option>E</option><option>O</option><option>M</option><option>S</option></select></label><label>Stop bits<select id="if-stop"><option value="1">1</option><option value="1.5">1.5</option><option value="2">2</option></select></label><label>Flow<select id="if-flow"><option value="none">None</option><option value="rtscts">RTS/CTS</option><option value="xonxoff">XON/XOFF</option></select></label><label>Framing<select id="if-framing"><option value="raw">Raw</option><option value="crlf">CRLF</option><option value="stx_etx">STX/ETX</option><option value="stx_etx_bcc">STX/ETX+BCC</option></select></label><button id="create-interface">Create Interface</button></div><div id="protocol-note" class="notice small"></div><div id="if-error" class="errorbox"></div></section>

<section class="card"><h3>Call Generator / Billing</h3><div class="row"><label>Call Accounting Interface<select id="call-if"></select></label><label>Mode<select id="call-mode"><option value="false">Immediate / Blind</option><option value="true">ENQ/ACK Transaction</option></select></label></div><div class="row"><label>Room<input id="call-room" value="101"></label><label>Number<input id="call-number" value="16155551212"></label><label>Duration sec<input id="call-duration" type="number" value="185"></label><label>Cost<input id="call-cost" type="number" step=".01" value="2.75"></label></div><button id="send-call">Record + Send Call</button><pre id="call-result">Ready.</pre></section>

<section class="card"><h3>Property Event Audit</h3><div class="row"><button id="refresh-events" class="secondary">Refresh Events</button></div><div id="events" class="scroll"></div></section>

<section class="card full"><h3>Live Wire Capture</h3><div class="row"><label>Interface<select id="capture-if"></select></label><button id="refresh-captures" class="secondary">Refresh</button><label>Auto refresh<select id="auto"><option value="0">Off</option><option value="1" selected>On</option></select></label></div><div id="captures" class="scroll"></div></section>
</div></div>
<script>
let protocols=[],properties=[],interfaces=[],currentProperty=null,selectedRoom=null;
const $=id=>document.getElementById(id);
async function api(path,opts={}){let r=await fetch(path,opts);if(!r.ok){let t=await r.text();throw new Error(t||r.statusText)}if(r.status===204)return null;return await r.json()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function jpost(path,body){return api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
function showError(id,e){let el=$(id);el.textContent=e?.message||String(e);el.style.display='block'}function clearError(id){$(id).style.display='none';$(id).textContent=''}
function selectedPropertyId(){return $('property-select').value||''}
function optionRows(items,valueKey='id',labelKey='name',empty='None'){return `<option value="">${esc(empty)}</option>`+items.map(x=>`<option value="${esc(x[valueKey])}">${esc(x[labelKey]||x[valueKey])}</option>`).join('')}
async function boot(){let [h,p,s]=await Promise.all([api('/api/v1/health'),api('/api/v1/protocols'),api('/api/v1/serial-ports')]);$('health').textContent=`v${h.version} · ${h.properties} propert${h.properties===1?'y':'ies'} · ${h.interfaces} interface(s)`;protocols=p.protocols.filter(x=>x.implemented);renderProtocols();renderSerial(s.ports);await refreshProperties();await refreshInterfaces();}
function renderSerial(ports){let current=$('if-serial').value;$('if-serial').innerHTML='<option value="">Select port</option>'+ports.map(x=>`<option value="${esc(x.device)}">${esc(x.device)}${x.description?' — '+esc(x.description):''}</option>`).join('');if([...$('if-serial').options].some(x=>x.value===current))$('if-serial').value=current}
function renderProtocols(){let purpose=$('if-purpose').value;let available=protocols.filter(x=>x.purpose===purpose);$('if-protocol').innerHTML=available.map(x=>`<option value="${esc(x.id)}">${esc(x.id)} · ${esc(x.maturity||'')}</option>`).join('');applyProtocolPreset()}
function applyProtocolPreset(){let p=protocols.find(x=>x.id===$('if-protocol').value);if(!p)return;let r=p.recommended||{};if(r.framing)$('if-framing').value=r.framing;$('protocol-note').textContent=`${p.maturity||'implemented'}: ${p.description||p.id}`}
async function refreshProperties(){let d=await api('/api/v1/properties');properties=d.properties;let old=$('property-select').value;$('property-select').innerHTML=optionRows(properties,'id','name','Select property');if(properties.some(x=>x.id===old))$('property-select').value=old;else if(properties.length)$('property-select').value=properties[0].id;let selected=$('property-select').value;$('if-property').innerHTML=optionRows(properties,'id','name','Unbound');if(selected&&[...$('if-property').options].some(x=>x.value===selected))$('if-property').value=selected;if(selected)await loadProperty(selected);else{currentProperty=null;renderProperty()}}
async function loadProperty(id){if(!id){currentProperty=null;renderProperty();return}currentProperty=await api(`/api/v1/properties/${encodeURIComponent(id)}`);renderProperty();await refreshEvents()}
function roomGuest(room){if(!room.active_stay_id||!currentProperty)return null;let stay=currentProperty.stays[room.active_stay_id];return stay?currentProperty.guests[stay.guest_id]:null}
function activeWakeup(roomNumber){if(!currentProperty)return null;return Object.values(currentProperty.wakeups).find(w=>w.room===roomNumber&&w.status==='scheduled')||null}
function renderProperty(){if(!currentProperty){$('property-metrics').innerHTML='';$('room-board').innerHTML='<div class="muted">Create or select a property.</div>';return}let rooms=Object.values(currentProperty.rooms);let occupied=rooms.filter(r=>r.active_stay_id).length;let wakeups=Object.values(currentProperty.wakeups).filter(w=>w.status==='scheduled').length;$('property-metrics').innerHTML=`<div class="metric"><b>${rooms.length}</b>Rooms</div><div class="metric"><b>${occupied}</b>Occupied</div><div class="metric"><b>${rooms.filter(r=>r.housekeeping==='dirty').length}</b>Dirty</div><div class="metric"><b>${wakeups}</b>Wakeups</div><div class="metric"><b>${currentProperty.calls.length}</b>Calls</div>`;rooms.sort((a,b)=>a.number.localeCompare(b.number,undefined,{numeric:true}));$('room-board').innerHTML=rooms.map(r=>{let g=roomGuest(r),w=activeWakeup(r.number),cls=['room',r.active_stay_id?'occupied':'',r.housekeeping==='dirty'?'dirty':'',r.out_of_order?'outoforder':'',selectedRoom===r.number?'selected-room':''].join(' ');let guest=g?`${g.last_name}${g.first_name?', '+g.first_name:''}`:'Vacant';return `<div class="${cls}" data-room="${esc(r.number)}"><div class="split"><span class="room-num">${esc(r.number)}</span><span class="pill">${esc(r.housekeeping)}</span></div><div class="room-sub">${esc(guest)}</div><div class="room-sub">Restr: ${esc(r.restriction)} · DND ${r.dnd?'ON':'off'} · MWI ${r.mwi_count}</div>${w?`<div class="room-sub">Wakeup ${esc(w.wakeup_time)}</div>`:''}</div>`}).join('')||'<div class="muted">No rooms yet. Use Add Rooms.</div>'}
async function createProperty(){try{clearError('property-error');await jpost('/api/v1/properties',{id:$('property-id').value,name:$('property-name').value,timezone:$('property-tz').value});await refreshProperties();$('property-select').value=$('property-id').value;await loadProperty($('property-id').value)}catch(e){showError('property-error',e)}}
async function seedDemo(){try{await api('/api/v1/scenarios/small-hotel?property_id=demo-hotel',{method:'POST'});await refreshProperties();$('property-select').value='demo-hotel';await loadProperty('demo-hotel');await refreshInterfaces()}catch(e){showError('property-error',e)}}
async function bulkRooms(){let p=selectedPropertyId();if(!p)return;try{await jpost(`/api/v1/properties/${encodeURIComponent(p)}/rooms/bulk`,{start:Number($('bulk-start').value),count:Number($('bulk-count').value),room_type:'standard'});await loadProperty(p)}catch(e){showError('property-error',e)}}
function selectRoom(n){selectedRoom=n;['guest-room','room-op-room','call-room'].forEach(id=>$(id).value=n);renderProperty()}
async function hotelOp(action){let p=selectedPropertyId(),iface=$('guest-if').value||null;try{let path,body;if(action==='checkin'){path='checkin';body={room:$('guest-room').value,first_name:$('guest-first').value,last_name:$('guest-last').value,language:$('guest-language').value,interface_name:iface}}else if(action==='checkout'){path='checkout';body={room:$('guest-room').value,interface_name:iface}}else if(action==='move'){path='move';body={room:$('guest-room').value,new_room:$('guest-new-room').value,interface_name:iface}}else if(action==='wakeup'){path='wakeups';body={room:$('guest-room').value,wakeup_time:$('wakeup-time').value,wakeup_date:$('wakeup-date').value,interface_name:iface}}else{path='wakeups/cancel';body={room:$('guest-room').value,interface_name:iface}}let d;if(p){d=await jpost(`/api/v1/properties/${encodeURIComponent(p)}/${path}`,body);await loadProperty(p)}else{if(!iface)throw new Error('Select a PMS interface for direct debug mode.');let eventAction=action==='wakeup'?'wakeup_set':action==='cancel-wakeup'?'wakeup_cancel':action;let event={action:eventAction,room:body.room,last_name:body.last_name||'',first_name:body.first_name||'',new_room:body.new_room||null,wakeup_time:body.wakeup_time||null,wakeup_date:body.wakeup_date||null,language:body.language||null};d=await jpost(`/api/v1/interfaces/${encodeURIComponent(iface)}/send/guest-event`,event)}$('guest-result').textContent=JSON.stringify(d,null,2);await refreshCaptures()}catch(e){$('guest-result').textContent=e.message}}
async function setRoomStatus(){let p=selectedPropertyId();if(!p)return;try{let room=$('room-op-room').value,d=await jpost(`/api/v1/properties/${encodeURIComponent(p)}/rooms/${encodeURIComponent(room)}/status`,{housekeeping:$('room-hk').value});$('room-result').textContent=JSON.stringify(d,null,2);await loadProperty(p)}catch(e){$('room-result').textContent=e.message}}
async function setRoomControls(){let p=selectedPropertyId();if(!p)return;let dnd=$('room-dnd').value,mwi=$('room-mwi').value;let body={restriction:$('room-restriction').value||null,dnd:dnd===''?null:dnd==='true',mwi_count:mwi===''?null:Number(mwi),language:$('room-language').value||null,voicemail_state:$('room-vm').value||null};try{let room=$('room-op-room').value,d=await jpost(`/api/v1/properties/${encodeURIComponent(p)}/rooms/${encodeURIComponent(room)}/controls`,body);$('room-result').textContent=JSON.stringify(d,null,2);await loadProperty(p)}catch(e){$('room-result').textContent=e.message}}
async function refreshInterfaces(){let d=await api('/api/v1/interfaces');interfaces=d.interfaces;$('interfaces').innerHTML=`<table><thead><tr><th>Interface</th><th>Property</th><th>Status</th><th>Clients</th><th>Actions</th></tr></thead><tbody>${interfaces.map(x=>`<tr><td><b>${esc(x.name)}</b><br><span class="small muted">${esc(x.protocol)} · ${esc(x.transport)}</span></td><td>${esc(x.property_id||'—')}</td><td><span class="status ${esc(x.state)}">${esc(x.state)}</span><br><span class="small">${esc(x.peer||x.last_error||'')}</span></td><td>${esc(x.connected_clients)}</td><td><button class="secondary" data-if-action="start" data-if-name="${esc(x.name)}">Start</button> <button class="secondary" data-if-action="stop" data-if-name="${esc(x.name)}">Stop</button> <button class="danger" data-if-action="delete" data-if-name="${esc(x.name)}">Delete</button></td></tr>`).join('')||'<tr><td colspan="5" class="muted">No interfaces configured.</td></tr>'}</tbody></table>`;let pms=interfaces.filter(x=>x.purpose==='pms'),ca=interfaces.filter(x=>x.purpose==='call_accounting');function fill(id,arr,label){let old=$(id).value;$(id).innerHTML=optionRows(arr,'name','name',label);if(arr.some(x=>x.name===old))$(id).value=old}fill('guest-if',pms,'No wire transmission');fill('call-if',ca,'Record only');fill('capture-if',interfaces,'Select interface');await refreshCaptures()}
async function createInterface(){let transport=$('if-transport').value,host=$('if-host').value,p=protocols.find(x=>x.id===$('if-protocol').value),recommended=p?.recommended||{};let options={...recommended,framing:$('if-framing').value};let body={name:$('if-name').value,purpose:$('if-purpose').value,protocol:$('if-protocol').value,property_id:$('if-property').value||null,transport,enabled:true,bind_host:transport==='tcp_server'?host:'0.0.0.0',host:transport==='tcp_client'?host:null,port:transport==='serial'?null:(Number($('if-port').value)||null),serial_device:transport==='serial'?$('if-serial').value:null,baud_rate:Number($('if-baud').value),data_bits:Number($('if-data').value),parity:$('if-parity').value,stop_bits:Number($('if-stop').value),flow_control:$('if-flow').value,options};try{clearError('if-error');await jpost('/api/v1/interfaces',body);await refreshInterfaces()}catch(e){showError('if-error',e)}}
async function interfaceAction(action,name,button){if(button?.disabled)return;try{clearError('if-error');if(action==='delete'&&!confirm(`Delete ${name}?`))return;if(button)button.disabled=true;let path=`/api/v1/interfaces/${encodeURIComponent(name)}`+(action==='delete'?'':`/${action}`);await api(path,{method:action==='delete'?'DELETE':'POST'});await refreshInterfaces()}catch(e){showError('if-error',e)}finally{if(button?.isConnected)button.disabled=false}}
async function sendCall(){let p=selectedPropertyId();if(!p){$('call-result').textContent='Select a property first.';return}let body={room:$('call-room').value,number:$('call-number').value,duration_seconds:Number($('call-duration').value),cost:Number($('call-cost').value),call_type:'D',interface_name:$('call-if').value||null,transactional:$('call-mode').value==='true'};try{let d=await jpost(`/api/v1/properties/${encodeURIComponent(p)}/calls`,body);$('call-result').textContent=JSON.stringify(d,null,2);await loadProperty(p);await refreshCaptures()}catch(e){$('call-result').textContent=e.message}}
async function refreshCaptures(){let n=$('capture-if').value;if(!n){$('captures').innerHTML='';return}try{let d=await api(`/api/v1/interfaces/${encodeURIComponent(n)}/captures?limit=150`);$('captures').innerHTML=`<table><thead><tr><th>Time</th><th>Dir</th><th>Peer / Note</th><th>Payload</th></tr></thead><tbody>${d.captures.slice().reverse().map(x=>`<tr><td class="nowrap">${esc(x.timestamp)}</td><td><b>${esc(x.direction.toUpperCase())}</b></td><td>${esc(x.peer||'')}<br><span class="small muted">${esc(x.note||'')}</span></td><td><code class="mono">${esc(x.hex)}</code><br><span class="small mono">${esc(x.text)}</span></td></tr>`).join('')}</tbody></table>`}catch(e){$('captures').textContent=e.message}}
async function refreshEvents(){let p=selectedPropertyId();if(!p){$('events').innerHTML='';return}try{let d=await api(`/api/v1/properties/${encodeURIComponent(p)}/events?limit=100`);$('events').innerHTML=`<table><thead><tr><th>Seq</th><th>Time</th><th>Event</th><th>Room</th><th>Data</th></tr></thead><tbody>${d.events.slice().reverse().map(x=>`<tr><td>${x.sequence}</td><td class="nowrap">${esc(x.timestamp)}</td><td>${esc(x.event_type)}</td><td>${esc(x.room||'')}</td><td class="small mono">${esc(JSON.stringify(x.payload))}</td></tr>`).join('')}</tbody></table>`}catch(e){$('events').textContent=e.message}}
$('if-purpose').onchange=renderProtocols;$('if-protocol').onchange=applyProtocolPreset;$('property-select').onchange=()=>loadProperty(selectedPropertyId());$('create-property').onclick=createProperty;$('seed-demo').onclick=seedDemo;$('refresh-property').onclick=()=>loadProperty(selectedPropertyId());$('bulk-rooms').onclick=bulkRooms;$('create-interface').onclick=createInterface;$('send-call').onclick=sendCall;$('set-room-status').onclick=setRoomStatus;$('set-room-controls').onclick=setRoomControls;$('refresh-captures').onclick=refreshCaptures;$('capture-if').onchange=refreshCaptures;$('refresh-events').onclick=refreshEvents;
document.addEventListener('click',e=>{let op=e.target.closest('[data-hotel-op]');if(op)hotelOp(op.dataset.hotelOp);let ib=e.target.closest('[data-if-action]');if(ib){e.preventDefault();interfaceAction(ib.dataset.ifAction,ib.dataset.ifName,ib)}let room=e.target.closest('[data-room]');if(room)selectRoom(room.dataset.room)});
setInterval(async()=>{if($('auto').value==='1'){try{await refreshInterfaces()}catch(e){}if(selectedPropertyId()){try{await loadProperty(selectedPropertyId())}catch(e){}}}},2500);boot().catch(e=>$('health').textContent=e.message);
</script></body></html>'''
