from __future__ import annotations


def html() -> str:
    return r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>InnAware PMS Emulator - Updates</title>
<style>
:root{font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#17202a;background:#eef1f4;--navy:#172b4d;--line:#d9e0e6;--muted:#677482;--green:#15803d;--red:#b91c1c;--amber:#a16207}
*{box-sizing:border-box}body{margin:0}.wrap{max-width:950px;margin:auto;padding:22px}.top{display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap}.card{background:white;border:1px solid var(--line);border-radius:12px;padding:16px;margin-top:14px;box-shadow:0 2px 7px #0000000b}.row{display:flex;gap:9px;flex-wrap:wrap;align-items:center}.grow{flex:1}.muted{color:var(--muted)}button,a.button{font:inherit;border:1px solid var(--navy);border-radius:7px;padding:9px 12px;background:var(--navy);color:white;cursor:pointer;text-decoration:none}button.secondary,a.secondary{background:white;color:var(--navy)}button:disabled{opacity:.5;cursor:not-allowed}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#e8edf3;font-size:12px}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#92400e}.bad{background:#fee2e2;color:#991b1b}pre{background:#111827;color:#d1fae5;padding:11px;border-radius:8px;white-space:pre-wrap;overflow:auto;max-height:280px}.settings label{display:block;margin:8px 0}.statusline{font-size:14px;margin:5px 0}.error{color:#991b1b;font-weight:650}
</style></head><body><div class="wrap">
<div class="top"><div><h1 style="margin:0">Update Center</h1><div class="muted">InnAware PMS Emulator application and protocol data</div></div><a class="button secondary" href="/">Back to Emulator</a></div>
<div class="card"><div class="row"><div class="grow"><h3 style="margin:0">Application Update</h3><div id="app-status" class="statusline muted">Loading...</div></div><button id="check">Check Now</button></div><div class="row" style="margin-top:10px"><button id="download" disabled>Download Verified Update</button><button id="install" class="secondary" disabled>Launch Installer</button><a id="release-link" class="button secondary" target="_blank" style="display:none">Release Notes</a></div></div>
<div class="card"><h3 style="margin-top:0">Protocol / Stub Pack</h3><div id="pack-status" class="statusline muted">Loading...</div><div class="row" style="margin-top:10px"><button id="pack-install" disabled>Download + Install Verified Pack</button></div><div class="muted" style="margin-top:10px">Protocol packs are data-only. They may add sanitized fixtures and technician profiles for protocol engines already included in the application. New executable protocol logic requires an application update.</div></div>
<div class="card settings"><h3 style="margin-top:0">Automatic Checks</h3><label><input type="checkbox" id="auto-app"> Check for application updates when the emulator starts</label><label><input type="checkbox" id="auto-pack"> Check for protocol-pack updates when the emulator starts</label><label><input type="checkbox" id="prerelease"> Include beta / prerelease releases</label><button id="save-settings" class="secondary">Save Settings</button></div>
<div class="card"><h3 style="margin-top:0">Details</h3><div id="error" class="error"></div><pre id="details">Loading update status...</pre></div>
</div><script>
const $=id=>document.getElementById(id);
async function api(path,opts={}){const r=await fetch(path,opts);const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(e){}if(!r.ok)throw new Error((d&&d.detail)||t||r.statusText);return d}
function render(status){$('details').textContent=JSON.stringify(status,null,2);$('error').textContent=status?.error||'';const app=status?.app;if(app){$('app-status').innerHTML=`Installed <b>${app.current_version}</b> · Latest <b>${app.latest_tag}</b> · ${app.update_available?'<span class="pill warn">Update available</span>':'<span class="pill good">Current</span>'}`;$('download').disabled=!app.update_available;$('release-link').style.display=app.release_url?'inline-block':'none';if(app.release_url)$('release-link').href=app.release_url}else{$('app-status').textContent=status?.error||'No release information available';$('download').disabled=true}
const pack=status?.protocol_pack;const directLocal=(pack&&Object.prototype.hasOwnProperty.call(pack,'installed'))?pack:null;const local=pack?.local||pack?.local_pack||status?.protocol_pack_local||directLocal;const remote=pack?.remote;if(pack){$('pack-status').innerHTML=`Installed pack: <b>${local?.pack_version||'none'}</b> · Remote: <b>${remote?.asset?.name||'none published'}</b> · ${pack.update_available?'<span class="pill warn">Update available</span>':'<span class="pill good">Current / none</span>'}`;$('pack-install').disabled=!pack.update_available}else{$('pack-status').textContent='No protocol-pack status available';$('pack-install').disabled=true}}
async function load(){try{const [s,settings]=await Promise.all([api('/api/v1/updates/status'),api('/api/v1/updates/settings')]);$('auto-app').checked=!!settings.check_app_updates_on_start;$('auto-pack').checked=!!settings.check_protocol_updates_on_start;$('prerelease').checked=!!settings.include_prereleases;render(s)}catch(e){$('error').textContent=e.message}}
$('check').onclick=async()=>{try{$('check').disabled=true;$('error').textContent='';render(await api('/api/v1/updates/check',{method:'POST'}))}catch(e){$('error').textContent=e.message}finally{$('check').disabled=false}}
$('download').onclick=async()=>{try{$('download').disabled=true;const d=await api('/api/v1/updates/app/download',{method:'POST'});$('details').textContent=JSON.stringify(d,null,2);$('install').disabled=false}catch(e){$('error').textContent=e.message}finally{$('download').disabled=false}}
$('install').onclick=async()=>{try{const d=await api('/api/v1/updates/app/launch',{method:'POST'});$('details').textContent=JSON.stringify(d,null,2)}catch(e){$('error').textContent=e.message}}
$('pack-install').onclick=async()=>{try{$('pack-install').disabled=true;const d=await api('/api/v1/updates/protocol-pack/install',{method:'POST'});$('details').textContent=JSON.stringify(d,null,2);await new Promise(r=>setTimeout(r,300));render(await api('/api/v1/updates/check',{method:'POST'}))}catch(e){$('error').textContent=e.message}finally{$('pack-install').disabled=false}}
$('save-settings').onclick=async()=>{try{const body={check_app_updates_on_start:$('auto-app').checked,check_protocol_updates_on_start:$('auto-pack').checked,include_prereleases:$('prerelease').checked};$('details').textContent=JSON.stringify(await api('/api/v1/updates/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),null,2)}catch(e){$('error').textContent=e.message}}
load();
</script></body></html>'''
