from __future__ import annotations


def html() -> str:
    return r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>InnAware PMS Emulator - Updates</title>
<style>
:root{font-family:system-ui,-apple-system,Segoe UI,sans-serif;color:#17202a;background:#eef3f8;--navy:#0f2747;--blue:#164e8f;--line:#d8e0e8;--muted:#667585;--green:#15803d;--red:#b91c1c;--amber:#a16207;--soft:#f7f9fc}
*{box-sizing:border-box}body{margin:0}.wrap{max-width:1050px;margin:auto;padding:24px}.top{display:flex;align-items:center;justify-content:space-between;gap:16px;flex-wrap:wrap}.brand h1{margin:0;font-size:30px}.brand .muted{margin-top:4px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(310px,1fr));gap:14px;margin-top:14px}.card{background:white;border:1px solid var(--line);border-radius:14px;padding:18px;box-shadow:0 3px 12px #0f27470d}.card h3{margin:0 0 9px}.row{display:flex;gap:9px;flex-wrap:wrap;align-items:center}.grow{flex:1}.muted{color:var(--muted)}button,a.button{font:inherit;border:1px solid var(--navy);border-radius:8px;padding:9px 13px;background:var(--navy);color:white;cursor:pointer;text-decoration:none}button:hover,a.button:hover{filter:brightness(1.08)}button.secondary,a.secondary{background:white;color:var(--navy)}button:disabled{opacity:.5;cursor:not-allowed}.pill{display:inline-block;padding:3px 8px;border-radius:999px;background:#e8edf3;font-size:12px}.good{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#92400e}.bad{background:#fee2e2;color:#991b1b}.settings label{display:block;margin:10px 0}.statusline{font-size:14px;margin:5px 0}.error{color:#991b1b;font-weight:650}.notice{background:var(--soft);border-left:4px solid var(--blue);padding:11px 12px;border-radius:8px;margin-top:10px;font-size:14px}.kv{display:grid;grid-template-columns:150px 1fr;gap:7px 12px;font-size:14px}.kv code{overflow-wrap:anywhere}.support-links{display:flex;gap:10px;flex-wrap:wrap;margin-top:10px}pre{background:#111827;color:#d1fae5;padding:12px;border-radius:9px;white-space:pre-wrap;overflow:auto;max-height:300px;margin-bottom:0}
</style></head><body><div class="wrap">
<div class="top"><div class="brand"><h1>Update Center</h1><div class="muted">Application updates, protocol packs, privacy settings, and support</div></div><a class="button secondary" href="/">Back to Emulator</a></div>
<div class="notice"><b>Official update source:</b> Application releases, protocol-pack releases, checksums, and release notes come from the InnAware PMS Emulator GitHub repository. The InnAware support site is for user help only.</div>
<div class="grid">
<div class="card"><div class="row"><div class="grow"><h3>Application Update</h3><div id="app-status" class="statusline muted">Loading...</div></div><button id="check">Check Now</button></div><div class="row" style="margin-top:12px"><button id="download" disabled>Download Verified Update</button><button id="install" class="secondary" disabled>Launch Installer</button><a id="release-link" class="button secondary" target="_blank" style="display:none">Release Notes</a><a class="button secondary" target="_blank" href="https://github.com/MusicCityTelecom/innaware-pms-emulator/releases">GitHub Releases</a></div><div class="notice">Update metadata and downloadable application artifacts are sourced from official GitHub Releases and SHA-256 verified before use.</div></div>
<div class="card"><h3>Protocol / Stub Pack</h3><div id="pack-status" class="statusline muted">Loading...</div><div class="row" style="margin-top:12px"><button id="pack-install" disabled>Download + Install Verified Pack</button></div><div class="notice">Protocol packs are data-only, published through GitHub Releases, and SHA-256 verified. New executable protocol logic still requires an application update.</div></div>
<div class="card settings"><h3>Preferences</h3><label><input type="checkbox" id="auto-app"> Check for application updates when the emulator starts</label><label><input type="checkbox" id="auto-pack"> Check for protocol-pack updates when the emulator starts</label><label><input type="checkbox" id="prerelease"> Include beta / prerelease releases</label><label><input type="checkbox" id="telemetry"> <b>Send anonymous usage statistics</b></label><div class="notice">Helps us understand how many installations of the InnAware PMS Emulator are in use. Telemetry contains only application version, platform, architecture, current protocol-pack version, a randomly generated installation identifier, and install/run events. No PMS data, hotel data, credentials, network configuration, or personally identifying information is transmitted.</div><button id="save-settings" class="secondary" style="margin-top:12px">Save Settings</button></div>
<div class="card"><h3>Telemetry / Installation ID</h3><div class="kv"><div class="muted">Status</div><div id="telemetry-status">Loading...</div><div class="muted">Install UUID</div><div><code id="telemetry-id">Loading...</code></div><div class="muted">Protocol pack</div><div><code id="telemetry-pack">Loading...</code></div></div><div class="row" style="margin-top:12px"><button id="copy-id" class="secondary">Copy UUID</button><a class="button secondary" target="_blank" href="https://github.com/MusicCityTelecom/innaware-pms-emulator/blob/main/docs/PRIVACY_TELEMETRY.md">Privacy Details</a></div></div>
<div class="card"><h3>Support</h3><div class="muted">Help using or troubleshooting the application. Updates and downloads are provided through GitHub Releases, not the support site.</div><div class="support-links"><a class="button" href="mailto:support@innawareucp.com">support@innawareucp.com</a><a class="button secondary" target="_blank" href="https://support.innawareucp.com">support.innawareucp.com</a></div></div>
</div>
<div class="card"><h3>Details</h3><div id="error" class="error"></div><pre id="details">Loading update status...</pre></div>
</div><script>
const $=id=>document.getElementById(id);
async function api(path,opts={}){const r=await fetch(path,opts);const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch(e){}if(!r.ok)throw new Error((d&&d.detail)||t||r.statusText);return d}
function render(status){$('details').textContent=JSON.stringify(status,null,2);$('error').textContent=status?.error||'';const app=status?.app;if(app){$('app-status').innerHTML=`Installed <b>${app.current_version}</b> · Latest <b>${app.latest_tag}</b> · ${app.update_available?'<span class="pill warn">Update available</span>':'<span class="pill good">Current</span>'}`;$('download').disabled=!app.update_available;$('release-link').style.display=app.release_url?'inline-block':'none';if(app.release_url)$('release-link').href=app.release_url}else{$('app-status').textContent=status?.error||'No release information available';$('download').disabled=true}
const pack=status?.protocol_pack;const directLocal=(pack&&Object.prototype.hasOwnProperty.call(pack,'installed'))?pack:null;const local=pack?.local||pack?.local_pack||status?.protocol_pack_local||directLocal;const remote=pack?.remote;if(pack){$('pack-status').innerHTML=`Installed pack: <b>${local?.pack_version||'built-in'}</b> · Remote: <b>${remote?.asset?.name||'none published'}</b> · ${pack.update_available?'<span class="pill warn">Update available</span>':'<span class="pill good">Current / none</span>'}`;$('pack-install').disabled=!pack.update_available}else{$('pack-status').textContent='No protocol-pack status available';$('pack-install').disabled=true}}
function renderTelemetry(t){$('telemetry-status').innerHTML=t.enabled?'<span class="pill good">Enabled</span>':'<span class="pill">Disabled</span>';$('telemetry-id').textContent=t.install_id||'unavailable';$('telemetry-pack').textContent=t.protocol_pack_version||'unknown'}
async function load(){try{const [s,settings,t]=await Promise.all([api('/api/v1/updates/status'),api('/api/v1/updates/settings'),api('/api/v1/telemetry/status')]);$('auto-app').checked=!!settings.check_app_updates_on_start;$('auto-pack').checked=!!settings.check_protocol_updates_on_start;$('prerelease').checked=!!settings.include_prereleases;$('telemetry').checked=!!settings.send_anonymous_usage_statistics;render(s);renderTelemetry(t)}catch(e){$('error').textContent=e.message}}
$('check').onclick=async()=>{try{$('check').disabled=true;$('error').textContent='';render(await api('/api/v1/updates/check',{method:'POST'}))}catch(e){$('error').textContent=e.message}finally{$('check').disabled=false}}
$('download').onclick=async()=>{try{$('download').disabled=true;const d=await api('/api/v1/updates/app/download',{method:'POST'});$('details').textContent=JSON.stringify(d,null,2);$('install').disabled=false}catch(e){$('error').textContent=e.message}finally{$('download').disabled=false}}
$('install').onclick=async()=>{try{const d=await api('/api/v1/updates/app/launch',{method:'POST'});$('details').textContent=JSON.stringify(d,null,2)}catch(e){$('error').textContent=e.message}}
$('pack-install').onclick=async()=>{try{$('pack-install').disabled=true;const d=await api('/api/v1/updates/protocol-pack/install',{method:'POST'});$('details').textContent=JSON.stringify(d,null,2);await new Promise(r=>setTimeout(r,300));render(await api('/api/v1/updates/check',{method:'POST'}));renderTelemetry(await api('/api/v1/telemetry/status'))}catch(e){$('error').textContent=e.message}finally{$('pack-install').disabled=false}}
$('save-settings').onclick=async()=>{try{const body={check_app_updates_on_start:$('auto-app').checked,check_protocol_updates_on_start:$('auto-pack').checked,include_prereleases:$('prerelease').checked,send_anonymous_usage_statistics:$('telemetry').checked};const saved=await api('/api/v1/updates/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('details').textContent=JSON.stringify(saved,null,2);renderTelemetry(await api('/api/v1/telemetry/status'))}catch(e){$('error').textContent=e.message}}
$('copy-id').onclick=async()=>{try{await navigator.clipboard.writeText($('telemetry-id').textContent||'');$('copy-id').textContent='Copied';setTimeout(()=>$('copy-id').textContent='Copy UUID',1200)}catch(e){$('error').textContent='Unable to copy the UUID automatically.'}}
load();
</script></body></html>'''
